// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIJKuz2MMzzSmR5_U2oyX_KV55ARVFekY',
    appId: '1:978225002289:web:29d46675413b38fc5a6210',
    messagingSenderId: '978225002289',
    projectId: 'restaurante-218f5',
    authDomain: 'restaurante-218f5.firebaseapp.com',
    storageBucket: 'restaurante-218f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqD0jKO5wwApQwC4kdRZNdQojCSLLwlLE',
    appId: '1:978225002289:android:ce530f4aa84568445a6210',
    messagingSenderId: '978225002289',
    projectId: 'restaurante-218f5',
    storageBucket: 'restaurante-218f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsOZkgmXAzmGknAdpRYeeTodL-GNKHHmk',
    appId: '1:978225002289:ios:cbc531268306ba105a6210',
    messagingSenderId: '978225002289',
    projectId: 'restaurante-218f5',
    storageBucket: 'restaurante-218f5.appspot.com',
    iosBundleId: 'com.example.lengs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsOZkgmXAzmGknAdpRYeeTodL-GNKHHmk',
    appId: '1:978225002289:ios:cbc531268306ba105a6210',
    messagingSenderId: '978225002289',
    projectId: 'restaurante-218f5',
    storageBucket: 'restaurante-218f5.appspot.com',
    iosBundleId: 'com.example.lengs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIJKuz2MMzzSmR5_U2oyX_KV55ARVFekY',
    appId: '1:978225002289:web:66f669169c918e4c5a6210',
    messagingSenderId: '978225002289',
    projectId: 'restaurante-218f5',
    authDomain: 'restaurante-218f5.firebaseapp.com',
    storageBucket: 'restaurante-218f5.appspot.com',
  );
}
